### ISSUE TITLE
Concerning a YouTube video~ 

### ISSUE THREAD

**Issue by zoltx23** [gdkchan/Ryujinx#106]
@gdkchan ~ 

**Since** I am not able to access Discord, and this is very good news; the YouTube video that displayed SMO running in RyujiNX as a mean of a joke. Has been DMCA'd by the team, and thus removed. 

**Emails are as follows:**

![image](https://user-images.githubusercontent.com/7658605/39247872-91e8cb38-4868-11e8-86cb-9d8fafd72550.png)
![image](https://user-images.githubusercontent.com/7658605/39247909-b4e66546-4868-11e8-917e-68f6dec14583.png)

**Comment by gdkchan** [comment]
This is not the place for this.
