### ISSUE TITLE
Ryujinx Icon

### ISSUE THREAD

**Issue by Mored1984** [gdkchan/Ryujinx#125]
This is **Ryujinx.ico** (512x512)

[Ryujinx.zip](https://github.com/gdkchan/Ryujinx/files/2023060/Ryujinx.zip)

or

http://s000.tinyupload.com/index.php?file_id=19308122091334523583

or

https://1drv.ms/u/s!Aplo7KUG2bc1ugPgCFkBO3SkWdbe

**Comment by AcK77** [comment]
Thanks but we already know how doing an ico file and right now we can’t add an icon to the executable.
