### ISSUE TITLE
Super Bomberman Thread 

### ISSUE THREAD

**Issue by NekokoTime** [gdkchan/Ryujinx#130]
![anotacao 11](https://user-images.githubusercontent.com/38867013/40784181-4251a72e-64bb-11e8-806a-972bdbd82467.png)

**Comment by AcK77** [comment]
Please, post that on discord. Not here. Thanks.

**Comment by zoltx23** [comment]
Also, I think that's the same Unimplemented service that is on the Comp database. Yep, it is. So could you stop making pointless PR's?

**Comment by Slick9000** [comment]
We already know the issue and it's in the compat database as said before. This isn't exactly a helpful PR.
