### ISSUE TITLE
Emulator wont boot

### ISSUE THREAD

**Issue by CommicKick69ing** [gdkchan/Ryujinx#162]
When ever I start the emulator it doesn't start and I don't know why?
![p_20180614_072047_vhdr_auto](https://user-images.githubusercontent.com/40266764/41409779-615c4fe4-6fa5-11e8-9ff7-7113c1f2c07a.jpg)

**Comment by AcK77** [comment]
Hi, as it’s explained in the Readme file. You need to install the OpenAL SDK to get audio support.

Thanks.

**Comment by CommicKick69ing** [comment]
thanks
