### ISSUE TITLE
AppVeyor Build Name Suggestion

### ISSUE THREAD

**Issue by zoltx23** [gdkchan/Ryujinx#17]
I suggest that setting the build name(s) should be set to have the compilation date on the end of the file name. 

**IE:** 
`ryujinx_%data_time%_unstable.zip` 

That would help to differentiate builds; and help with not having to replace an existing download. 
I am pretty sure that AppVeyor supports custom File name support and build scripts.  

~Dr.Hacknik

**Comment by Kumoashi** [comment]
I completely agree with this idea, and I think it should be implemented as soon as possible. As it currently stands, it is nearly impossible to know when a new build of Ryujinx has been released.

**Comment by zoltx23** [comment]
Currently trying to get the site to show the version number (via JavaScript)~ Although, it seems it doesn't quite work when I am using a `try` object along with a `catch` object. 

Coming from C# , Javascript shouldn't be that different. Just a slightly different formatting. 
Am I doing something incorrect here? I probably am. 

**Snip snap~**

```js
/*
Thanks to MS-DOS over at Discord for suggesting this code!
*/
var xhr = new XMLHttpRequest();
xhr.onload = function() {
    try {
        xhr.open('GET', 'https://ci.appveyor.com/api/projects/gdkchan/ryujinx');
        if (xhr.status === 200) {
            var res = JSON.parse(xhr.responseText);
            console.log("Build Version : " + res.build.version);
            document.getElementById("ver_num").innerHTML = res.build.version;
        }
    }
} catch (err) {
    document.getElementById("ver_num").innerHTML = "Failed";
}
xhr.send();
```

**Comment by MerryMage** [comment]
@zoltx23 https://jsfiddle.net/n2szmdhg/5/

**Comment by zoltx23** [comment]
Thanks. I'll commit those changes and see if it works correctly.
