### ISSUE TITLE
Games?

### ISSUE THREAD

**Issue by GitHubDan01** [gdkchan/Ryujinx#182]
There is no information on where to download games such as currently running sonic mania

**Comment by simonmkwii** [comment]
This is gonna be a looooooooong day...

**Comment by simonmkwii** [comment]
I'm convinced that you can't be serious, I assume you're just trolling.

**Comment by Slick9000** [comment]
@GitHubDan01 The games are to be dumped from your switch. If you don't own one, then that's you. We won't support piracy.

**Comment by GitHubDan01** [comment]
Right i see well i do own a switch but i am unsure how to dump them to pc 

also i've been attempting to use Ryujinx for the past 5 minutes was attempting to use a homebrew game just to test it and nothing was working

**Comment by Soikow** [comment]
Maybe you aren't doing something right, ask for help in the discord

**Comment by gdkchan** [comment]
We don't support piracy, you should dump your own games.
