### ISSUE TITLE
Puyo Puyo Tetris glitches

### ISSUE THREAD

**Issue by Dantttt** [gdkchan/Ryujinx#203]
There are some glitches that makes the info box bigger than usual and there are still some visual bugs

**Comment by gdkchan** [comment]
This issue is too vague. Show where exactly you're seeing those issues, with images demonstrating what is wrong and how it is supposed to look like.

**Comment by Dantttt** [comment]
Sorry,it was a computer problem,but if I find more issues, I'll make it on github!
