### ISSUE TITLE
Touchscreen coordinates reported incorrectly when Windows DPI != 96

### ISSUE THREAD

**Issue by Ghabry** [gdkchan/Ryujinx#43]
My system has a DPI setting of 200% and ryujinx creates a emulator window of 2560x1440. I already set the compatibility setting for DPI scaling to "Application" to exclude a Windows-side emulation but this behaviour appears to be on purpose.

This hugher window results in incorrect touch coordinates being reported that must be divided by the DPI scale factor.

First related search result:
https://stackoverflow.com/questions/5977445/how-to-get-windows-display-settings

**Comment by emmauss** [comment]
thanks for the report. what app are you running

**Comment by emmauss** [comment]
test this #41

**Comment by emmauss** [comment]
@Ghabry  please check if issue still exists on latest master

**Comment by Ghabry** [comment]
is fixed, thanks!
