### ISSUE TITLE
NATIVE_WINDOW_TRANSFORM*

### ISSUE THREAD

**Issue by Cpasjuste** [gdkchan/Ryujinx#46]
Hi,

There is a problem with the NATIVE_WINDOW_TRANSFORM* handling. I made a sample program to test rotation, this one works fine on the device but Ryujinx does have wrong rotations. 
You can find the sample program here : https://github.com/Cpasjuste/nx-cmake/blob/master/source/main.c#L93
I didn't had the time to take a closer look at Ryujinx sources, but i guess it's a very easy fix.

**Comment by Cpasjuste** [comment]
To be more clear, it seems NATIVE_WINDOW_TRANSFORM_FLIP_H and NATIVE_WINDOW_TRANSFORM_FLIP_V are inverted (at least with libnx).  Flipping them does make things works.

**Comment by gdkchan** [comment]
Thank you for reporting this issue! Can you attach a compiled nro here so I can test on the emulator?

**Comment by Cpasjuste** [comment]
Sure :

- What Ryujinx currently does (code working correctly on the device) : http://files.mydedibox.fr/files/Dev/nx/rotation_wrong.nro
- What Ryujinx should do (with "RYUJINX" defined to 1 in the sources) : http://files.mydedibox.fr/files/Dev/nx/rotation_correct.nro

**Comment by gdkchan** [comment]
both rotation_wrong and rotation_correct produces the same result for me.

**Comment by Cpasjuste** [comment]
I guess i mixed the binaries :x 
The image should just rotate 90° clockwise at each key press, which is the case (with the current code i posted) on real hw but not in Ryujinx. Ryujinx does flip H and V transformation (90° and 180° rotation in my code are wrong in Ryujinx).

**Comment by gdkchan** [comment]
ah sorry, I didn't know I had to press a button to rotate it XD the binaries are correct.

**Comment by gdkchan** [comment]
Rotation issue should be fixed by eacd432387677dc0513255f8c3661f5c3ef05d65.
Currently looking into the scale issue.

**Comment by gdkchan** [comment]
5d8a615c21eff7888ff4e36c122123560bcb0886 adds support for scaling using crop, but I couldn't tests the cases where top != 0 or left != 0 because no homebrew apps I have here uses it, would like to test that before I close this issue.

**Comment by Cpasjuste** [comment]
Hi @gdkchan , sorry for the late reply. 
Was able to test yesterday, all is working perferctly : rotation/scaling.. Great changes. 
I was not able to test the cases where top != 0 or left != 0, i'll let you know if i ever take a closer look.

**Comment by gdkchan** [comment]
Ok, thanks! If you do test the top/left != 0 cases and find issues on it, please open a new issue here.
