### ISSUE TITLE
Appstore Homebrew Missing Text

### ISSUE THREAD

**Issue by Gamedev1909** [gdkchan/Ryujinx#82]
https://www.youtube.com/watch?v=cS_bsSOpDt4 as the title says app store is missing text

**Comment by Cyuubi** [comment]
This is because shared fonts aren't implemented.

**Comment by Gamedev1909** [comment]
sad i even have those

**Comment by gdkchan** [comment]
should be at the root of the sdcard (on windows, %AppData%\RyuFs\sdmc

**Comment by Gamedev1909** [comment]
booting windows to check thats works

**Comment by Gamedev1909** [comment]
still textless but at least its in the right p[lace now
